
RSC_PATH    = File.join('/Applications/Logic Pro X.app/Contents/Resources')
PLIST_FILE  = `cd '#{RSC_PATH}' && find . -name  logicpro\*.plist`.gsub('./', '').chomp
URL     = 'http://audiocontentdownload.apple.com/lp10_ms3_content_2016/'
ROOT		= File.dirname(__FILE__)
TMPDIR 	= File.join(ROOT, '/tmp')
PARENT	= File.expand_path('..', Dir.pwd)
PLIST   = File.join(RSC_PATH, PLIST_FILE)
JSN     = File.join(TMPDIR, 'content.json')
DWN_LNK = File.join(PARENT, 'download_links')
DWN_LST = File.join(DWN_LNK, 'links.txt')
JSN_DIR	= File.join(DWN_LNK, 'json')
JSN_FLE	= File.join(JSN_DIR, "logicpro_content.json")
INSTALL = File.join(PARENT, 'installers')
REPORT	= File.join(DWN_LNK, 'report.txt')
CAT			= %w(AppleLoops JamPacks GarageBand Instruments Alchemy IRs DrumKits)
PKG 		= 'Packages'
PKG_ID	= 'PackageID'
DLN			= 'DownloadName'
C_ALCH	=	'ContainsAlchemyFiles'
