name: LPX_LINKS Build
on: [push, pull_request]
jobs:
 test:
  name: Test and Lint
  runs-on: ubuntu-latest
  strategy:
   matrix:
    ruby: ['2.6', '2.7', '3.0']
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Set up Ruby
    uses: ruby/setup-ruby@v1
    with:
     ruby-version: ${{ matrix.ruby }}
     bundler-cache: true
  - name: Install dependencies
    run: bundle install
  - name: Run Linter
    run: bundle exec standard
  - name: Run Tests
    run: bundle exec rspec spec/*
  - name: Static Analysis
    run: bundle exec reek
